name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.9.0+1
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  grpc: ^3.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  firebase_auth_rest: ^2.0.1
  universal_io: ^2.0.4

dev_dependencies:
  test: ^1.17.7
  pedantic: ^1.11.0
