name: firedart
description: An incomplete, dart-native implementation of the Firebase SDK.
version: 0.6.3
author: Daniel Cachapa <cachapa@gmail.com>
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.0+2
  grpc: ^2.1.3
  protobuf: ^1.0.1
  fixnum: ^0.10.11

dev_dependencies:
  test: ^1.6.4
  pedantic: ^1.8.0+1
