name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.8.0+1
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.12.0
  grpc: ^2.1.0
  protobuf: ^1.0.0
  fixnum: ^0.10.0

dev_dependencies:
  test: ^1.14.0
  pedantic: ^1.9.0
